name: Latest Blog Posts
on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@riginoommen"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
          template: "- [$title]($url)"
          commit_message: "📝 Updated Medium blog posts"
          committer_username: "blog-bot"
          committer_email: "blog-bot@users.noreply.github.com"
